### ISSUE TITLE
DDTI is not displaying target info

### ISSUE THREAD

**Issue by remainvigilant** [IAmLokken/DeepDungeonOverlay#9]
I've tried uninstalling and reinstalling, reloading the plugin several times, messing with options, nothing is working. The DDO plugin works just fine, but any target information on the DDO plugin or the DDTI plugin do not display any information.

![image](https://user-images.githubusercontent.com/12685314/166289582-d49fba79-0c51-488c-a0bd-6feb8b445eb9.png)

In fact, DDTI does not even display until I force it to from the DDTI options menu "Enable overlay".

**Comment by IAmLokken** [comment]
Hi Remainvigilant!  Appreciate the issue!

I have heard similar things a couple of times since the patch.  Each time the FFXIV plugin or OverlayPlugin needed to be updated.  I have also heard it can be finicky with prompting an update when starting and re-starting ACT.

I am on FFXIV_ACT_Plugin version 2.6.5.1 and OverlayPlugin version 0.18.2.0.

Also are you sure that your game client language and FFXIV_ACT_Plugin language are set to the same language?

![image](https://user-images.githubusercontent.com/46271810/166310602-20cf24f9-4f6f-4d12-a1b5-df15564f6fc0.png)

**Comment by remainvigilant** [comment]
Yep, that was it. The OverlayPlugin needed to be updated. Usually I get prompts for updates, but i guess not today! Thanks! Sorry for making you worry, haha.

**Comment by IAmLokken** [comment]
Thanks for the kind words and no worries at all, just glad it was an easy fix!  Good luck on your next run!

**Comment by aahvocado** [comment]
Hi @IAmLokken I'm having the same issue. OverlayPlugin says it's the latest, as is ACT itself. Any suggestions?
